### ISSUE TITLE
Requirement not found (Linux)

### ISSUE THREAD

**Issue by DeastinY** [rrgeorge/FoundryToEncounter#2]
Hi, thanks for the great work!
If running linux `python-magic-bin` can not be install, but you need to install `python-magic `instead :+1:

**Comment by rrgeorge** [comment]
Ironically, I do most of my development on Linux, and I was originally using python-magic, but I switched to python-magic-bin for ease on Windows and Mac.

**Comment by DeastinY** [comment]
Well, that's pretty funny :grin: 
I'm not that experienced in working with different OS versions / imports in the code, so not sure how to fix this, but just replacing the import makes it work if using linux :+1:
