### ISSUE TITLE
Are Encounters / Tokens added to maps as well?

### ISSUE THREAD

**Issue by DeastinY** [rrgeorge/FoundryToEncounter#3]
I did not find much information except for `"Scenes are converted to maps with an encounter for assinged tokens."`.
For the module I exported (adding the `-c` flag) there are no tokens on the map.
Is this something that's not yet implemented or did I do something wrong here?

**Comment by rrgeorge** [comment]
If there were tokens on the map to be converted, they would be made into an encounter under the map. See the attached photo. 
![79F1075D-A94E-4D0C-B3F6-1471B30D4562](https://user-images.githubusercontent.com/8526392/111853038-858e3380-88d6-11eb-93de-b7672462c17b.jpeg)

**Comment by rrgeorge** [comment]
Support was added in v1.8.1
